
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pirátská strana | Šablona stránek
email: to@pirati.cz
description: > # this means to ignore newlines until "baseurl:"
  Zde doplně popis webu
url: "https://pirati.cz" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

paginate_path: "/aktuality/:num/"
paginate: 11

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - jekyll-theme-pirati.gemspec
  - node_modules
  - package.json
  - package-lock.json
  - vendor
  - assets/js
  - config

sass:
  style: compressed
  load_paths:
    - _sass
    - node_modules

js_base_url: '/assets/js/'

# Make sure webpack-generated assets are not purged by Jekyll
keep_files:
  - assets/js

permalink: /aktuality/:title.html

collections:
  people:
    output: true
    permalink: /lide/:path/

  program:
    output: true
    permalink: /komunalni-volby/:path/

defaults:   # defaults values for collection scope
  -
    scope:
      path: "_people"
    values:
      layout: "person"
      rbar: "people, foto"
  -
    scope:
      path: "_program"
    values:
      layout: "program-post"
      rbar: "garant, program"

emptyArray: []

organization:
  name: Jmeno skupiny používající web - př Pirástá strana
  shortName: Název skupiny
  contactUid: jakub.pirat
  email: example@pirati.cz
  phone: +420 777 123 456 789
  address: |
    Piratská planeta 1
    100 00 Pirátsko
  residenceImg:
  mapLink: https://mapy.cz/zakladni?base=ophoto&q=Radou%C5%A1ova%2014,%20Chrudim
  redmineLink: https://redmine.pirati.cz/projects


# Image banner on the top of the homepage. Useful for promoting current events.
homepageBanner:
  display: false
  link: /komunalni-volby/
  title: Komunální volby 2018
  breakpoint: 640 # breakpoint in pixels when to start showing `default` instead of `mobile`
  image:
    default: path/to/img.jpg
    mobile: path/to/img.jpg

calendar:
  title: Celostátní kalendář
  page: https://calendar.google.com/calendar/embed?showTitle=0&amp;showNav=0&amp;showDate=0&amp;showPrint=0&amp;showTabs=0&amp;showCalendars=0&amp;showTz=0&amp;mode=AGENDA&amp;height=500&amp;wkst=2&amp;hl=cs&amp;bgcolor=%23FFFFFF&amp;src=nk73m1m89vhf5g2vojp6tnqe58%40group.calendar.google.com&ctz=Europe%2FPrague&amp;color=%232952A3

facebook:
  loadSDK: true
  profilePage:
  appId: 1526197851008996

twitter:
  loadSDK: true
  profile: PiratskaStrana

instagram:
  profilePage: https://www.instagram.com/pirati.cz/

gplus:
  profilePage: https://plus.google.com/u/0/+piratskastrana

flicker:
  profilePage: https://www.flickr.com/photos/pirati/

forum:
  page: https://forum.pirati.cz/

github:
  url: https://github.com/pirati-web/jekyll-theme-pirati/
  branch: master


assets:
  source_maps: true
  compression: true
  gzip: false
  plugins:
    css: { autoprefixer: {}}
    img:
      optim:
        jpegoptim:
          strip: all
          max_quality: 80
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"
  sources:
    - node_modules
    - assets/css
    - assets/fonts
    - assets/video
    - assets/img
    - _sass
